// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetradeBE.Data;

#nullable disable

namespace RetradeBE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630071524_RemoveAuctionDepositTransactions")]
    partial class RemoveAuctionDepositTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetradeBE.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsPasswordSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_password_set");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login_at");

                    b.Property<bool?>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("must_change_password");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Provider")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("AccountId")
                        .HasName("account_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.AccountRole", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.HasKey("AccountId", "RoleId")
                        .HasName("account_role_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("account_role", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Address", b =>
                {
                    b.Property<string>("AddressId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("district_id");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("integer")
                        .HasColumnName("province_id");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("receiver_name");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("receiver_phone");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("street");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("WardCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ward_code");

                    b.HasKey("AddressId")
                        .HasName("address_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Attributes", b =>
                {
                    b.Property<string>("AttributeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("attribute_id");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("data_type");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("AttributeId")
                        .HasName("attributes_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("attributes", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Auction", b =>
                {
                    b.Property<string>("AuctionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auction_id");

                    b.Property<decimal?>("BuyNowPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("buy_now_price");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_price");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<decimal?>("MinIncrement")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_increment");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<string>("SellerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<decimal?>("StartingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("starting_price");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WinnerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("winner_id");

                    b.HasKey("AuctionId")
                        .HasName("auction_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.HasIndex("WinnerId");

                    b.ToTable("auction", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.AuctionDeposit", b =>
                {
                    b.Property<string>("AuctionDepositId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auction_deposit_id");

                    b.Property<string>("AuctionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auction_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<bool?>("PolicyAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("policy_accepted");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("AuctionDepositId")
                        .HasName("auction_deposit_pkey");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("auction_deposit", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Banner", b =>
                {
                    b.Property<string>("BannerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("banner_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("text")
                        .HasColumnName("redirect_url");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("BannerId")
                        .HasName("banner_pkey");

                    b.ToTable("banner", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Bid", b =>
                {
                    b.Property<string>("BidId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bid_id");

                    b.Property<string>("AuctionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auction_id");

                    b.Property<decimal?>("BidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bid_amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("BidId")
                        .HasName("bid_pkey");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("bid", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CategoryId")
                        .HasName("category_pkey");

                    b.HasIndex("ParentId");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.CategoryImage", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_id");

                    b.Property<string>("ImageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CategoryId", "ImageId")
                        .HasName("category_image_pkey");

                    b.HasIndex("ImageId");

                    b.ToTable("category_image", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Chat", b =>
                {
                    b.Property<string>("ChatId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chat_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MessageType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("message_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("RoomId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room_id");

                    b.Property<string>("SenderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ChatId")
                        .HasName("chat_pkey");

                    b.HasIndex("RoomId");

                    b.HasIndex("SenderId");

                    b.ToTable("chat", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.ChatRoom", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room_id");

                    b.Property<string>("BuyerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<string>("SellerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoomId")
                        .HasName("chat_room_pkey");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("chat_room", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Image", b =>
                {
                    b.Property<string>("ImageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_id");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("alt_text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.HasKey("ImageId")
                        .HasName("image_pkey");

                    b.ToTable("image", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.MyService", b =>
                {
                    b.Property<string>("UserSubId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_sub_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("UserSubId")
                        .HasName("my_service_pkey");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("my_service", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.MyVoucher", b =>
                {
                    b.Property<string>("UserVoucherId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_voucher_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("VoucherId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voucher_id");

                    b.HasKey("UserVoucherId")
                        .HasName("my_voucher_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("my_voucher", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("notification_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("notification_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Offer", b =>
                {
                    b.Property<string>("OfferId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("offer_id");

                    b.Property<string>("BuyerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<decimal?>("OfferPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("offer_price");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("OfferId")
                        .HasName("offer_pkey");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ProductId");

                    b.ToTable("offer", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_id");

                    b.Property<string>("AddressSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("address_snapshot");

                    b.Property<string>("AuctionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auction_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime?>("ExpectedDeliveryTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expected_delivery_time");

                    b.Property<decimal?>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("final_amount");

                    b.Property<string>("OfferId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("offer_id");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_code");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("ReturnReason")
                        .HasColumnType("text")
                        .HasColumnName("return_reason");

                    b.Property<string>("SellerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seller_id");

                    b.Property<decimal?>("ShippingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("shipping_fee");

                    b.Property<string>("ShippingProvider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shipping_provider");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tracking_code");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("VoucherId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voucher_id");

                    b.HasKey("OrderId")
                        .HasName("Order_pkey");

                    b.HasIndex("AuctionId");

                    b.HasIndex("OfferId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("RetradeBE.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_id");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_id");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("payment_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_id");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("condition");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("integer")
                        .HasColumnName("height_cm");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("LengthCm")
                        .HasColumnType("integer")
                        .HasColumnName("length_cm");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("SellerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WeightGram")
                        .HasColumnType("integer")
                        .HasColumnName("weight_gram");

                    b.Property<int?>("WidthCm")
                        .HasColumnType("integer")
                        .HasColumnName("width_cm");

                    b.HasKey("ProductId")
                        .HasName("product_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.ProductAttribute", b =>
                {
                    b.Property<string>("ProductAttributeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_attribute_id");

                    b.Property<string>("AttributeId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("attribute_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("ProductAttributeId")
                        .HasName("product_attribute_pkey");

                    b.HasIndex("AttributeId");

                    b.HasIndex("ProductId");

                    b.ToTable("product_attribute", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.ProductImage", b =>
                {
                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<string>("ImageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsMain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_main");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("ProductId", "ImageId")
                        .HasName("product_image_pkey");

                    b.HasIndex("ImageId");

                    b.ToTable("product_image", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.RefundRequest", b =>
                {
                    b.Property<string>("RefundRequestId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("refund_request_id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("BankAccountHolder")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_account_holder");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bank_account_number");

                    b.Property<string>("BankName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_id");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text")
                        .HasColumnName("reject_reason");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("RefundRequestId")
                        .HasName("refund_request_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("refund_request", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Review", b =>
                {
                    b.Property<string>("ReviewId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("review_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("order_id");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("ReviewerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("SellerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ReviewId")
                        .HasName("review_pkey");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("SellerId");

                    b.HasIndex(new[] { "OrderId", "ReviewerId" }, "review_order_id_reviewer_id_key")
                        .IsUnique();

                    b.ToTable("review", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.ReviewReport", b =>
                {
                    b.Property<string>("ReviewReportId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("review_report_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reporter_id");

                    b.Property<string>("ReviewId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("review_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ReviewReportId")
                        .HasName("review_report_pkey");

                    b.HasIndex(new[] { "ReporterId" }, "IX_review_report_reporter_id");

                    b.HasIndex(new[] { "ReviewId" }, "IX_review_report_review_id");

                    b.HasIndex(new[] { "ReviewedBy" }, "IX_review_report_reviewed_by");

                    b.HasIndex(new[] { "ReviewId", "ReporterId" }, "review_report_review_id_reporter_id_key")
                        .IsUnique();

                    b.ToTable("review_report", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("role_pkey");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.ServiceSubscription", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("service_id");

                    b.Property<string>("BenefitsDescription")
                        .HasColumnType("text")
                        .HasColumnName("benefits_description");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_role");

                    b.HasKey("ServiceId")
                        .HasName("service_subscription_pkey");

                    b.ToTable("service_subscription", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<int?>("FlagCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("flag_count");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("User_pkey");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RetradeBE.Models.UserFavorite", b =>
                {
                    b.Property<string>("FavoriteId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("favorite_id");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("FavoriteId")
                        .HasName("user_favorite_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("user_favorite", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.UserFollow", b =>
                {
                    b.Property<string>("FollowId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("follow_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FollowedUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("followed_user_id");

                    b.Property<string>("FollowerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("follower_id");

                    b.HasKey("FollowId")
                        .HasName("user_follow_pkey");

                    b.HasIndex("FollowedUserId");

                    b.HasIndex("FollowerId");

                    b.ToTable("user_follow", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.UserReport", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason");

                    b.Property<string>("ReporterId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reporter_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TargetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("target_type");

                    b.HasKey("ReportId")
                        .HasName("user_report_pkey");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ReviewedBy");

                    b.ToTable("user_report", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.UserSearch", b =>
                {
                    b.Property<string>("SearchId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("search_id");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Keyword")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("keyword");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("SearchId")
                        .HasName("user_search_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("user_search", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Voucher", b =>
                {
                    b.Property<string>("VoucherId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voucher_id");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discount_type");

                    b.Property<decimal?>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiration_date");

                    b.Property<decimal?>("MaxDiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("max_discount_value");

                    b.Property<decimal?>("MinOrderValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("min_order_value");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SellerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VoucherId")
                        .HasName("voucher_pkey");

                    b.HasIndex("SellerId");

                    b.ToTable("voucher", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Wishlist", b =>
                {
                    b.Property<string>("WishlistId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wishlist_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("WishlistId")
                        .HasName("wishlist_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("wishlist", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.WishlistItem", b =>
                {
                    b.Property<string>("WishlistItemId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wishlist_item_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProductId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_id");

                    b.Property<string>("WishlistId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("wishlist_id");

                    b.HasKey("WishlistItemId")
                        .HasName("wishlist_item_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex("WishlistId");

                    b.ToTable("wishlist_item", (string)null);
                });

            modelBuilder.Entity("RetradeBE.Models.Account", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("Account")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_account_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.AccountRole", b =>
                {
                    b.HasOne("RetradeBE.Models.Account", "Account")
                        .WithMany("AccountRole")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("fk_ar_account");

                    b.HasOne("RetradeBE.Models.Role", "Role")
                        .WithMany("AccountRole")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_ar_role");

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RetradeBE.Models.Address", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("Address")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_address_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.Attributes", b =>
                {
                    b.HasOne("RetradeBE.Models.Category", "Category")
                        .WithMany("Attributes")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_attr_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RetradeBE.Models.Auction", b =>
                {
                    b.HasOne("RetradeBE.Models.Product", "Product")
                        .WithMany("Auction")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_auction_product");

                    b.HasOne("RetradeBE.Models.User", "Seller")
                        .WithMany("AuctionSeller")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("fk_auction_seller");

                    b.HasOne("RetradeBE.Models.User", "Winner")
                        .WithMany("AuctionWinner")
                        .HasForeignKey("WinnerId")
                        .HasConstraintName("fk_auction_winner");

                    b.Navigation("Product");

                    b.Navigation("Seller");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("RetradeBE.Models.AuctionDeposit", b =>
                {
                    b.HasOne("RetradeBE.Models.Auction", "Auction")
                        .WithMany("AuctionDeposit")
                        .HasForeignKey("AuctionId")
                        .HasConstraintName("fk_ad_auction");

                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("AuctionDeposit")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_ad_user");

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.Bid", b =>
                {
                    b.HasOne("RetradeBE.Models.Auction", "Auction")
                        .WithMany("Bid")
                        .HasForeignKey("AuctionId")
                        .HasConstraintName("fk_bid_auction");

                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("Bid")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_bid_user");

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.Category", b =>
                {
                    b.HasOne("RetradeBE.Models.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_category_parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("RetradeBE.Models.CategoryImage", b =>
                {
                    b.HasOne("RetradeBE.Models.Category", "Category")
                        .WithMany("CategoryImage")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("fk_ci_category");

                    b.HasOne("RetradeBE.Models.Image", "Image")
                        .WithMany("CategoryImage")
                        .HasForeignKey("ImageId")
                        .IsRequired()
                        .HasConstraintName("fk_ci_image");

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RetradeBE.Models.Chat", b =>
                {
                    b.HasOne("RetradeBE.Models.ChatRoom", "Room")
                        .WithMany("Chat")
                        .HasForeignKey("RoomId")
                        .HasConstraintName("fk_chat_room");

                    b.HasOne("RetradeBE.Models.User", "Sender")
                        .WithMany("Chat")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("fk_chat_sender");

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("RetradeBE.Models.ChatRoom", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "Buyer")
                        .WithMany("ChatRoomBuyer")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("fk_cr_buyer");

                    b.HasOne("RetradeBE.Models.Product", "Product")
                        .WithMany("ChatRoom")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_cr_product");

                    b.HasOne("RetradeBE.Models.User", "Seller")
                        .WithMany("ChatRoomSeller")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("fk_cr_seller");

                    b.Navigation("Buyer");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("RetradeBE.Models.MyService", b =>
                {
                    b.HasOne("RetradeBE.Models.ServiceSubscription", "Service")
                        .WithMany("MyService")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_ms_service");

                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("MyService")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_ms_user");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.MyVoucher", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("MyVoucher")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_mv_user");

                    b.HasOne("RetradeBE.Models.Voucher", "Voucher")
                        .WithMany("MyVoucher")
                        .HasForeignKey("VoucherId")
                        .HasConstraintName("fk_mv_voucher");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("RetradeBE.Models.Notification", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("Notification")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_notify_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.Offer", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "Buyer")
                        .WithMany("Offer")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("fk_offer_buyer");

                    b.HasOne("RetradeBE.Models.Product", "Product")
                        .WithMany("Offer")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_offer_product");

                    b.Navigation("Buyer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RetradeBE.Models.Order", b =>
                {
                    b.HasOne("RetradeBE.Models.Auction", "Auction")
                        .WithMany("Order")
                        .HasForeignKey("AuctionId")
                        .HasConstraintName("fk_order_auction");

                    b.HasOne("RetradeBE.Models.Offer", "Offer")
                        .WithMany("Order")
                        .HasForeignKey("OfferId")
                        .HasConstraintName("fk_order_offer");

                    b.HasOne("RetradeBE.Models.Product", "Product")
                        .WithMany("Order")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_order_product");

                    b.HasOne("RetradeBE.Models.User", "Seller")
                        .WithMany("OrderSeller")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("fk_order_seller");

                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("OrderUser")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_order_user");

                    b.HasOne("RetradeBE.Models.Voucher", "Voucher")
                        .WithMany("Order")
                        .HasForeignKey("VoucherId")
                        .HasConstraintName("fk_order_voucher");

                    b.Navigation("Auction");

                    b.Navigation("Offer");

                    b.Navigation("Product");

                    b.Navigation("Seller");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("RetradeBE.Models.Payment", b =>
                {
                    b.HasOne("RetradeBE.Models.Order", "Order")
                        .WithMany("Payment")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_payment_order");

                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("Payment")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_payment_user");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.Product", b =>
                {
                    b.HasOne("RetradeBE.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_product_category");

                    b.HasOne("RetradeBE.Models.User", "Seller")
                        .WithMany("Product")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("fk_product_seller");

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("RetradeBE.Models.ProductAttribute", b =>
                {
                    b.HasOne("RetradeBE.Models.Attributes", "Attribute")
                        .WithMany("ProductAttribute")
                        .HasForeignKey("AttributeId")
                        .HasConstraintName("fk_pa_attr");

                    b.HasOne("RetradeBE.Models.Product", "Product")
                        .WithMany("ProductAttribute")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_pa_product");

                    b.Navigation("Attribute");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RetradeBE.Models.ProductImage", b =>
                {
                    b.HasOne("RetradeBE.Models.Image", "Image")
                        .WithMany("ProductImage")
                        .HasForeignKey("ImageId")
                        .IsRequired()
                        .HasConstraintName("fk_pi_image");

                    b.HasOne("RetradeBE.Models.Product", "Product")
                        .WithMany("ProductImage")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_pi_product");

                    b.Navigation("Image");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RetradeBE.Models.RefundRequest", b =>
                {
                    b.HasOne("RetradeBE.Models.Order", "Order")
                        .WithMany("RefundRequest")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_rr_order");

                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("RefundRequest")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_rr_user");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.Review", b =>
                {
                    b.HasOne("RetradeBE.Models.Order", "Order")
                        .WithMany("Review")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_review_order");

                    b.HasOne("RetradeBE.Models.User", "Reviewer")
                        .WithMany("ReviewReviewer")
                        .HasForeignKey("ReviewerId")
                        .HasConstraintName("fk_review_reviewer");

                    b.HasOne("RetradeBE.Models.User", "Seller")
                        .WithMany("ReviewSeller")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("fk_review_seller");

                    b.Navigation("Order");

                    b.Navigation("Reviewer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("RetradeBE.Models.ReviewReport", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "Reporter")
                        .WithMany("ReviewReportReporter")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_report_reporter");

                    b.HasOne("RetradeBE.Models.Review", "Review")
                        .WithMany("ReviewReport")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_report_review");

                    b.HasOne("RetradeBE.Models.User", "ReviewedByNavigation")
                        .WithMany("ReviewReportReviewedByNavigation")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("fk_review_report_reviewer");

                    b.Navigation("Reporter");

                    b.Navigation("Review");

                    b.Navigation("ReviewedByNavigation");
                });

            modelBuilder.Entity("RetradeBE.Models.UserFavorite", b =>
                {
                    b.HasOne("RetradeBE.Models.Category", "Category")
                        .WithMany("UserFavorite")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_ufav_category");

                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("UserFavorite")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_ufav_user");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.UserFollow", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "FollowedUser")
                        .WithMany("UserFollowFollowedUser")
                        .HasForeignKey("FollowedUserId")
                        .HasConstraintName("fk_uf_followed");

                    b.HasOne("RetradeBE.Models.User", "Follower")
                        .WithMany("UserFollowFollower")
                        .HasForeignKey("FollowerId")
                        .HasConstraintName("fk_uf_follower");

                    b.Navigation("FollowedUser");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("RetradeBE.Models.UserReport", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "Reporter")
                        .WithMany("UserReportReporter")
                        .HasForeignKey("ReporterId")
                        .HasConstraintName("fk_ur_reporter");

                    b.HasOne("RetradeBE.Models.User", "ReviewedByNavigation")
                        .WithMany("UserReportReviewedByNavigation")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("fk_ur_reviewer");

                    b.Navigation("Reporter");

                    b.Navigation("ReviewedByNavigation");
                });

            modelBuilder.Entity("RetradeBE.Models.UserSearch", b =>
                {
                    b.HasOne("RetradeBE.Models.Category", "Category")
                        .WithMany("UserSearch")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("fk_us_category");

                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("UserSearch")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_us_user");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.Voucher", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "Seller")
                        .WithMany("Voucher")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("fk_voucher_seller");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("RetradeBE.Models.Wishlist", b =>
                {
                    b.HasOne("RetradeBE.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_wishlist_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RetradeBE.Models.WishlistItem", b =>
                {
                    b.HasOne("RetradeBE.Models.Product", "Product")
                        .WithMany("WishlistItem")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_wi_product");

                    b.HasOne("RetradeBE.Models.Wishlist", "Wishlist")
                        .WithMany("WishlistItem")
                        .HasForeignKey("WishlistId")
                        .HasConstraintName("fk_wi_wishlist");

                    b.Navigation("Product");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("RetradeBE.Models.Account", b =>
                {
                    b.Navigation("AccountRole");
                });

            modelBuilder.Entity("RetradeBE.Models.Attributes", b =>
                {
                    b.Navigation("ProductAttribute");
                });

            modelBuilder.Entity("RetradeBE.Models.Auction", b =>
                {
                    b.Navigation("AuctionDeposit");

                    b.Navigation("Bid");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RetradeBE.Models.Category", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("CategoryImage");

                    b.Navigation("InverseParent");

                    b.Navigation("Product");

                    b.Navigation("UserFavorite");

                    b.Navigation("UserSearch");
                });

            modelBuilder.Entity("RetradeBE.Models.ChatRoom", b =>
                {
                    b.Navigation("Chat");
                });

            modelBuilder.Entity("RetradeBE.Models.Image", b =>
                {
                    b.Navigation("CategoryImage");

                    b.Navigation("ProductImage");
                });

            modelBuilder.Entity("RetradeBE.Models.Offer", b =>
                {
                    b.Navigation("Order");
                });

            modelBuilder.Entity("RetradeBE.Models.Order", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("RefundRequest");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("RetradeBE.Models.Product", b =>
                {
                    b.Navigation("Auction");

                    b.Navigation("ChatRoom");

                    b.Navigation("Offer");

                    b.Navigation("Order");

                    b.Navigation("ProductAttribute");

                    b.Navigation("ProductImage");

                    b.Navigation("WishlistItem");
                });

            modelBuilder.Entity("RetradeBE.Models.Review", b =>
                {
                    b.Navigation("ReviewReport");
                });

            modelBuilder.Entity("RetradeBE.Models.Role", b =>
                {
                    b.Navigation("AccountRole");
                });

            modelBuilder.Entity("RetradeBE.Models.ServiceSubscription", b =>
                {
                    b.Navigation("MyService");
                });

            modelBuilder.Entity("RetradeBE.Models.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Address");

                    b.Navigation("AuctionDeposit");

                    b.Navigation("AuctionSeller");

                    b.Navigation("AuctionWinner");

                    b.Navigation("Bid");

                    b.Navigation("Chat");

                    b.Navigation("ChatRoomBuyer");

                    b.Navigation("ChatRoomSeller");

                    b.Navigation("MyService");

                    b.Navigation("MyVoucher");

                    b.Navigation("Notification");

                    b.Navigation("Offer");

                    b.Navigation("OrderSeller");

                    b.Navigation("OrderUser");

                    b.Navigation("Payment");

                    b.Navigation("Product");

                    b.Navigation("RefundRequest");

                    b.Navigation("ReviewReportReporter");

                    b.Navigation("ReviewReportReviewedByNavigation");

                    b.Navigation("ReviewReviewer");

                    b.Navigation("ReviewSeller");

                    b.Navigation("UserFavorite");

                    b.Navigation("UserFollowFollowedUser");

                    b.Navigation("UserFollowFollower");

                    b.Navigation("UserReportReporter");

                    b.Navigation("UserReportReviewedByNavigation");

                    b.Navigation("UserSearch");

                    b.Navigation("Voucher");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("RetradeBE.Models.Voucher", b =>
                {
                    b.Navigation("MyVoucher");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RetradeBE.Models.Wishlist", b =>
                {
                    b.Navigation("WishlistItem");
                });
#pragma warning restore 612, 618
        }
    }
}
